// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CSVtoJSONConverter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("row_count")]
        public long RowCount { get; set; }

        [JsonProperty("column_count")]
        public long ColumnCount { get; set; }

        [JsonProperty("columns")]
        public string[] Columns { get; set; }

        [JsonProperty("json")]
        public Json[] Json { get; set; }
    }

    public partial class Json
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("age")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Age { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }
    }
}
